### ISSUE TITLE
Add assays_dictionary as a special cdx_core field type

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#280]
- [ ] Update cdx_core definition to handle assays_dictionary
```
  assays:
    type: assays_dictionary
    value_fields:
      name:
        searchable: true
      result:
        type: enum
        searchable: true
        options:
          - positive
          - negative
          - n/a
      quantitative_result:
        type: integer
```
- [ ] Handle assays_dictionary type in tests schema
```
"assays": {
  "title": "Assays",
  "type": "object",
  "keys" : [
    "mtb",
    "rif"
  ],
  "additionalProperties": {
    "type": "object",
    "properties": {
      "name": {
        "title": "Name",
        "type": "string",
        "searchable": true
      },
      "result": {
        "title": "Result",
        "type": "string",
        "enum": [
          "positive",
          "negative",
          "n/a"
        ],
        "values": {
          "positive": {
            "name": "Positive",
            "kind": "positive"
          },
          "negative": {
            "name": "Negative",
            "kind": "negative"
          },
          "n/a": {
            "name": "N/A"
          }
        },
        "searchable": true
      },
      "quantitative_result": {
        "title": "Quantitative Result",
        "type": "integer",
        "searchable": false
      }
    }
  },
  "searchable": true
}
```
- [ ] Handle assays_dictionary type in ES mapping
- [ ] Handle assays_dictionary type in manifests
```
    "test.assays.mtb.qualitative_result" : {
      "script" : "
        if(message['Result'].match(/.*tuberculosis.*/)){
          'positive'
        } else {
          'negative'
        }"
    },
    "test.assays.mtb.name" : { "mtb" },
```
- [ ] Validate that `test.assays.mtb.qualitative_result` matches one of the conditions defined in the upper section of the manifest
- [ ] Allow queries like `test.assays=mtb,rif` and `test.assays.mtb=positive`
- [ ] Ensure InSTEDD Hub still works
- [ ] Ensure NNDD still works
