### ISSUE TITLE
Allow querying Encounters and Tests separately

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#414]
An encounter should contain:
```
     - Encounter:
          - id
          - uuid
          - patient_age
          - start_time
          - end_time
          - Diagnosis:
               - mtb:
                    - result: positive
                    - quantitative_result: 98
               - rif:
                    - result: negative
```

An API user should be able to filter encounter by its status: "any", "confirmed" or "unconfirmed". Confirmed cases will be those with user-confirmed diagnostics. Skip "phantom" encounters. See #413.

Add a different endpoint to query Encounters.

Move the patient_age from the test to the encounter.

The encounter start_date should be the smaller of all the start dates of all the tests. Mind the test updates.

The end_date should be the end time of the last test or the time of the diagnostic, if available.
